using System;
using System.Threading.Tasks;

namespace UpdatePackagesWithSuffix
{
    class Program
    {       
        static async Task Main(string suffix, string feedUrl, string projectFile)
        {
            if (suffix == null || feedUrl == null || projectFile == null)
            {
                PrintHelp();
                return;
            }

            var feed = new NugetFeed(feedUrl);
            var project = new ProjectFile(projectFile);
            foreach (var packageReference in project.PackageReferences)
            {
                // <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
                string packageName = packageReference.Attribute("Include").Value;
                string lastVersion = await feed.FindLastVersionAsync(packageName, suffix);
                if (lastVersion != null)
                {
                    Console.WriteLine($"Found version {packageName} {lastVersion}");
                    packageReference.Attribute("Version").Value = lastVersion;
                }
            }
            project.Save();
        }

        private static int PrintHelp() 
            => System.CommandLine.DragonFruit.CommandLine.ExecuteAssembly(typeof(AutoGeneratedProgram).Assembly, new string[] { "--help" }, "");

    }
}
